package ru.lab6.Commands;

public enum CommandType {
    ADD, CLEAR,ADD_IF_MAX, EXECUTE_SCRIPT, HELP, INFO, REMOVE_BY_ID, REMOVE_LOWER,
     SHOW, UPDATE, FILTER_STARTS_WITH_NAME, PRINT_FIELD_DESCENDING_DISTANCE, PRINT_UNIQUE_DISTANCE,
    REMOVE_FIRST
}